### ISSUE TITLE
Cell size dynamically

### ISSUE THREAD

**Issue by Muvidevelopers** [pitiphong-p/CollectionViewShelfLayout#3]
Can we change the cell size dynamically when loading?

**Comment by pitiphong-p** [comment]
Do you mean self-sizing cells?

**Comment by Muvidevelopers** [comment]
Yes, Like What I do, I use flow layout's sizeForcell method and there I get the image size which will be there in cell from API and from size of image, I calculate the size and return however with this I can not access that method.
Could you please help

**Comment by ghost** [comment]
Is it possible to have different cell heights per section? 

Ex. 
Section1 = 172, 
Section2 = 203, 
Section3 = 141

**Comment by pitiphong-p** [comment]
We do not support the variable cell size yet. If you are interested, you can implement that feature and open a PR to me

**Comment by ghost** [comment]
@pitiphong-p I've worked around the codebase for a while but was unsuccessful. The protocol for flow layout, when applied to your code and my view controller never gets run. 

If you can give me some hints on where you think the problem lies, I would be more than happy to work on it again.

Thanks 3P.

**Comment by pitiphong-p** [comment]
@datureezy Sorry for this late reply. I was very busy at the time you posted this comment and I forgot to reply to you. Please accept my apology.
Since there are a few requests on this feature, I think I'll try to implement it in the next version (which I'm about to start to work on it).

**Comment by pitiphong-p** [comment]
@datureezy Sorry for this late reply. I was very busy at the time you posted this comment and I forgot to reply to you. Please accept my apology.
Since there are a few requests on this feature, I think I'll try to implement it in the next version (which I'm about to start to work on it).

**Comment by pitiphong-p** [comment]
I have implemented this feature and published it. Please try with the latest release version 0.6.2
