### ISSUE TITLE
Different sizes for different rows

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [pitiphong-p/CollectionViewShelfLayout#5]
Is it possible to set different row height?

Check the screenshot attached
![simulator screen shot - iphone 6s - 2017-10-17 at 11 29 31](https://user-images.githubusercontent.com/21377276/31649021-757f4a50-b32e-11e7-86c4-672b8232afde.png)

**Comment by pitiphong-p** [comment]
It’s not supported right out of the box yet. However you can implement that and open a PR back to this repo. I can help you guide on how to do it

**Comment by vaibhav-varshaaweblabs** [comment]
@pitiphong-p Yes, please help me out how to do that. What changes do I need to do in the  **CollectionViewShelfLayout.swift** file?

**Comment by pitiphong-p** [comment]
You can add that feature by letting CollectionViewShelfLayout having its own delegate and add an optional method for that in this delegate and having the layout to ask its delegate when the layout is calculating its layout informations.

**Comment by pitiphong-p** [comment]
I have implemented this feature and published it. Please try with the latest release version 0.6.2
