### ISSUE TITLE
Bad instruction

### ISSUE THREAD

**Issue by kchen97** [pitiphong-p/CollectionViewShelfLayout#7]
`return sectionHeaderViewsLayoutAttributes[indexPath.section]`

Gives a bad instruction unless I cast indexPath into NSIndexPath

**Comment by pitiphong-p** [comment]
Oh thank you for your report. May I ask that you implement the custom height of Section Header, right?

**Comment by kchen97** [comment]
`let shelfLayout: CollectionViewShelfLayout = {
        let layout = CollectionViewShelfLayout()
        layout.cellSize = CGSize(width: UIScreen.main.bounds.width, height: 38)
        layout.sectionHeaderHeight = 38
        layout.spacing = 0
        return layout
    }()`

**Comment by pitiphong-p** [comment]
I fixed this issue on #9 could you pull the branch, try your code on that branch and tell me if this issue is fixed.

**Comment by pitiphong-p** [comment]
Please try again with the `0.6.4` version
