### ISSUE TITLE
cells not appearing

### ISSUE THREAD

**Issue by kchen97** [pitiphong-p/CollectionViewShelfLayout#8]
In an app I am building I am dynamically creating sections based on data I get back from my database. If I scroll all the way to the end, and then a section is dynamically created above it with different # of items that new section retains the scroll position of the section thats scrolled all the way to the end.

Is there a way to fix this so that all sections scroll to the first item when the section is created?

**Comment by pitiphong-p** [comment]
Do you have a sample code or sample project that can reproduce this issue?
